### PR TITLE
Allow specifying api_version via starting_struct for OAuth login

### PR DESCRIPTION
**Pull request by craiglyons**
## Problems
* Specifying `api_version` in the starting_struct passed to `login` for OAuth did not result in the services api versions being changed from the default of v41.0.
* The default API version is 41.0, 43.0 is now available.

## Solution
* Apply the specified starting_struct's `api_version` value during OAuth/login
* Bump default API version

### CODE REVIEW

**Comment by craiglyons** [comment]
@jeffweiss Any concerns with this PR? It'd be nice to get my project off of my fork so I can make more contributions.

**Comment by mmrobins** [comment]
Hey @craiglyons, Jeff isn't really maintaining this anymore since he's not using it for work, but I am.  I had forgotten to look through the PRs for awhile, but I'll try to look at this today.

**Comment by mmrobins** [comment]
Looks good, thanks for writing the tests, makes it easy to review 👍

**Comment by craiglyons** [comment]
Ah right - thanks @mmrobins

**Comment by mmrobins** [comment]
Release 0.8.2 with this change

**Comment by craiglyons** [comment]
✨ thanks a ton for this & the typespec fixes, and the quick publish to Hex!

**Pull request merged**
